schema_version: 1

context:
  name: libmed
  version: 4.1.1
  build: 21
  sha256: fe1e80c836150ff27049b291fe2f9a11eda9ef9831311df9e39ba16a63c392a0
  mpi: mpi or 'nompi'
  mpi_prefix: nompi

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # url: https://files.salome-platform.org/Salome/medfile/med-{{ version }}.tar.gz # blacklisting conda forge
  url: https://github.com/Krande/med-copy/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  patches:
    # Part of this patch is required to add a few system definitions which
    # should indicate that they are using the 1.10 API not the 1.6 API
    # https://github.com/HDFGroup/hdf5/issues/3797
    - patches/ignore-hdf5-bounds-check-cmake.patch
    - patches/ignore-hdf5-bounds-check-source.patch
    - if: win
      then: patches/disable-fortran.patch
    - patches/do_not_modify_windows_path.patch
    - patches/install-in-runtime-and_archive.patch
    # without this patch, OSX finds the system python since it is a newer version
    # I (hmaarrfk) am about 90% sure it is because SWIG + CMake 3.12 FindPython + OSX
    # has some bugs... so for OSX (and linux), we just fallback to the standard
    # build process
    - if: win
      then: patches/cmake-modern-python.patch
    - patches/do-not-make-symlinks-on-windows.patch
    - patches/link-privately.patch
    - patches/py313_support.patch

build:
  # Per https://conda-forge.org/docs/maintainer/knowledge_base.html#preferring-a-provider-usually-nompi
  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi
  number: ${{ build|int + 100 if mpi == "nompi" else build|int }}
  string: ${{ mpi_prefix }}_h${{ hash }}_${{ build }}
  skip: (osx or win) and mpi != "nompi"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: not win
      then: ${{ compiler('fortran') }}
    - swig 4.2.1.*
    - cmake
    - if: win
      then: ninja
    - if: unix
      then: make
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - python
    # Leave one bare "hdf5" here with no build number constraints
    # So that the pinning can take effect
    # https://github.com/conda-forge/libmed-feedstock/issues/77
    - hdf5
    - if: mpi != "nompi"
      then: hdf5 * ${{ mpi_prefix }}_*
    - if: mpi == "nompi"
      then: hdf5 * nompi_*
    - zlib
    - if: mpi != "nompi" or mpi != "nompi"
      then: mpi or 'nompi'.*
  run:
    - python
    - if: mpi != "nompi" or mpi != "nompi"
      then: mpi or 'nompi'.*
    - ${{ pin_compatible('hdf5', upper_bound='x.x') }}
  run_exports:
    - ${{ pin_subpackage(name, 'x.x') }} ${{ mpi_prefix }}_*

tests:
  - python:
      imports:
        - med
  - files:
      recipe:
        - tests
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - pytest
    script:
      - if: unix
        then: test -f ${PREFIX}/lib/libmed${SHLIB_EXT}
      - if: linux
        then: nm ${PREFIX}/lib/libmedC.so | grep MEDlibraryNumVersion
      - if: build_platform == target_platform
        then: pytest -v tests

about:
  license: LGPL-3.0-only
  license_file: COPYING
  summary: "MED : interoperable format for data interchange between mesh based solvers."
  description: |
    The purpose of the MED module is to provide a standard for storing and recovering computer data associated to numerical meshes and fields, and to facilitate the exchange between codes and solvers.
  homepage: https://www.salome-platform.org/user-section/about/med
  repository: https://git.salome-platform.org/gitweb/?p=modules/med.git;a=summary
  documentation: http://www.salome-platform.org/

extra:
  recipe-maintainers:
    - Krande
    - ldallolio
    - looooo
    - ldallolio-irt

