travis:
  secure:
    BINSTAR_TOKEN: w+trXnDXFHt09k8oes1MBPB64As74IDvG5zQKPm9JN/6U4vGWjN1pU+F2OOLlAZO/mXdlJ9O5wB+z07JM8VPNq0+d+35yd460D1bdeObwdhiomF7C7zevyrtVhey8nO0bIkvb26ZnpB5rjmju4LfZO+1OfaV85bNThGvKj7ZJCYCagArJQlphSFqDgvvDIe1r3aTc2EyijcHGN5I60PuxO6CARkw1GegaJd8GdNpzj3igQqvaMmWF0+ds1WkdD/mP+F7/P0qy1JfW6cy2Ge9GSMLDYZnbr4gvwTnQQBfeioURRa3Te2caZnFUbFx+MFNZh56ZxPZzOYNWluEsOrPMgKVGLXuaPQDAEY7woaNWdE0eXeYlbjz07FxjBe4HOhnd666M0mC7wrU5ORAHHtGgFtR5GEmURfaX6om4rrMeI7JDqVjYMKkcNDJP1++oJne1OmbtzEPDcgUWqrNoLSvEiKZ36AKLDWBHN/zv0O7hPcJaLhEbOZEIAmN3ZlNfdzXeAUXrL9Ld3axu/VoGMuJC5SMbrmzg4dWhJvRy/4qig4chFLCIvO2YPeLB0Q6hywCTmEFhlTBadaSMPFng5yqNl+iA+LwZCzroQJcMMptBZlRBhl4AQUUC35MtXp9MoQ9ShIZ5JwQvCkidmv5mV4F4Te3hOiUfmxJ4XWjaGzysWk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
